CREATE TABLE IF NOT EXISTS Kafka_SystemMetrics
(
    CollectedAt String, 
    CollectedAt_Shamsi String, 
    WindowsSid String,
    ComputerName String,
    WindowsUsername_RunAdmin String,
    WindowsUsername String,
    MotherboardSerial String,
    CPUJson String,
    TotalRamMb Float64,
    UsedRamMb Float64,
    FreeRamMb Float64,
    SystemUptimeSeconds UInt64,
    ActiveProcesses UInt32,
    ActiveThreads UInt32,
    OpenHandles UInt64,
    BootTime String, 
    FailedLoginAttempts Int32,
    AntivirusStatus String,
    FirewallStatus String,
    UsbDevicesCount UInt16,
    StorageDetailsJson String,
    NetworkDetailsJson String,
    NetworkTraceJson String,
    DiskModelsJson String,
    TopProcessesJson String,
    DiskHealthStatusJson String,
    CriticalSystemEventsJson String ,
    ChromeHistoryJson String
) ENGINE = Kafka()
SETTINGS
    kafka_broker_list = 'kafka:9092',
    kafka_topic_list = 'advanced_system_metrics_topic',
    kafka_group_name = 'clickhouse_group_metrics_v3',
    kafka_format = 'JSONEachRow';