CREATE MATERIALIZED VIEW IF NOT EXISTS MV_SystemMetrics_To_Target TO SystemMetrics AS
SELECT
    toDateTime(CollectedAt) AS CollectedAt, 
    CollectedAt_Shamsi, 
    WindowsSid,
    WindowsUsername,
    WindowsUsername_RunAdmin,
    ComputerName,
    CPUJson,
    MotherboardSerial,
    TotalRamMb,
    UsedRamMb,
    FreeRamMb,
    SystemUptimeSeconds,
    ActiveProcesses,
    ActiveThreads,
    OpenHandles,
    parseDateTime64BestEffortOrZero(BootTime, 7) AS BootTime, 
    FailedLoginAttempts,
    AntivirusStatus,
    FirewallStatus,
    UsbDevicesCount,
    StorageDetailsJson,
    NetworkDetailsJson,
    NetworkTraceJson,
    DiskModelsJson,
    TopProcessesJson,
    DiskHealthStatusJson,
    CriticalSystemEventsJson,
    ChromeHistoryJson
FROM Kafka_SystemMetrics;